title: "Analysing Malware One Sample At A Time"
author: Liam Chugg
description: "A collection of practical malware analysis and DFIR techniques, tools, and write-ups."

# Email / Social media usernames for Minima theme:
# All of these are optional — add or remove as needed.
# email: "example@mail.com"
# twitter_username: ""
github_username: "MZHeader"
linkedin_username: "liam-chugg"
# facebook_username: ""
# flickr_username: ""
# instagram_username: ""
# pinterest_username: ""
# youtube_username: ""
# googleplus_username: ""

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################

remote_theme: pages-themes/modernist@v0.2.0

# RSS feed and analytics
# rss: rss
google_analytics: G-48M02RY99Q

# Kramdown markdown engine settings
kramdown:
  syntax_highlighter_opts:
    disable: true

# Plugins for feed and sitemap generation
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Use first heading as page title for posts & collections
titles_from_headings:
  strip_title: true
  collections: true

# Default front matter for posts
defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
